// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChZ3R9Q-GQBbWJY4CE-i-TgOCj4LEi2Rc',
    appId: '1:1022160774217:web:031a5d764e968955d94b98',
    messagingSenderId: '1022160774217',
    projectId: 'noteappnoteify',
    authDomain: 'noteappnoteify.firebaseapp.com',
    storageBucket: 'noteappnoteify.appspot.com',
    measurementId: 'G-1GQF88DRJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL-V-wyh0It32vKEY1T0UdxwELpYZ5EPU',
    appId: '1:1022160774217:android:40dfa2a8d1840f67d94b98',
    messagingSenderId: '1022160774217',
    projectId: 'noteappnoteify',
    storageBucket: 'noteappnoteify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1GQvpA0BiLTmhju_Sg8-w7mHA7CNDZFA',
    appId: '1:1022160774217:ios:07df287d0e716ddad94b98',
    messagingSenderId: '1022160774217',
    projectId: 'noteappnoteify',
    storageBucket: 'noteappnoteify.appspot.com',
    iosBundleId: 'com.example.myNoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1GQvpA0BiLTmhju_Sg8-w7mHA7CNDZFA',
    appId: '1:1022160774217:ios:07df287d0e716ddad94b98',
    messagingSenderId: '1022160774217',
    projectId: 'noteappnoteify',
    storageBucket: 'noteappnoteify.appspot.com',
    iosBundleId: 'com.example.myNoteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChZ3R9Q-GQBbWJY4CE-i-TgOCj4LEi2Rc',
    appId: '1:1022160774217:web:a9ce3705cbe9ca80d94b98',
    messagingSenderId: '1022160774217',
    projectId: 'noteappnoteify',
    authDomain: 'noteappnoteify.firebaseapp.com',
    storageBucket: 'noteappnoteify.appspot.com',
    measurementId: 'G-240LD4NP39',
  );
}
